### ISSUE TITLE
Non-maven related directory

### ISSUE THREAD

**Issue by AntonisGkortzis** [nafsikalampr/UnitTesting-seip#5]
Please add the ```target``` in your ```.gitignore``` file and also remove the uploaded directory from your repository. 

Non-maven files and folders should not be committed.

**Comment by nafsikalampr** [comment]
done i think?

**Comment by AntonisGkortzis** [comment]
Sorry do disappoint you but the ```target``` is still there. 
To remove a directory from your online repo you should execute the following
```git rm -r --cached myFolder```
